{
 "title": "Host Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host_ip",
    "label": "主机IP地址",
    "query": {
     "query": "label_values(node_cpu_seconds_total,ip)"
    }
   },
   {
    "name": "device",
    "label": "设备名",
    "query": {
     "query": "label_values(node_disk_info,device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU 监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "主机 CPU 使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg_over_time(\n  (\n    sum by (ip) (\n      rate(node_cpu_seconds_total{job=\"static\",mode=\"idle\",ip=~\"$host_ip\"}[$__rate_interval])\n    )\n    / on (ip)\n    count by (ip) (\n      node_cpu_seconds_total{job=\"static\",mode=\"idle\",ip=~\"$host_ip\"}\n    )\n  )[$__range:]\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "主机 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (ip, mode) (rate(node_cpu_seconds_total{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval]))/\non (ip) group_left count by (ip) (\n  node_cpu_seconds_total{job=\"static\",ip=~\"$host_ip\",mode=\"idle\"}\n)",
     "legendFormat": "{{mode}}-{{ip}}"
    },
    {
     "expr": "sum by (ip) (rate(node_cpu_guest_seconds_total{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval]))/ on (ip) group_left count by (ip) (\n  node_cpu_seconds_total{job=\"static\",ip=~\"$host_ip\",mode=\"idle\"}\n)",
     "legendFormat": "guest-{{ip}}"
    },
    {
     "expr": "1- (sum by (ip) (rate(node_cpu_seconds_total{job=\"static\", mode=\"idle\",ip=~\"$host_ip\"}[$__rate_interval])) / on (ip) group_left count by (ip) (\n  node_cpu_seconds_total{job=\"static\",ip=~\"$host_ip\",mode=\"idle\"}\n))",
     "legendFormat": "usage-{{ip}}"
    }
   ]
  },
  {
   "title": "CPU Load1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load1{job=\"static\",ip=~\"$host_ip\"}[$__range])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "CPU Load5",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{job=\"static\",ip=~\"$host_ip\"}[$__range])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "CPU Load15",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{job=\"static\",ip=~\"$host_ip\"}[$__range])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "CPU 负载",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "node_load1{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "load1-{{ip}}"
    },
    {
     "expr": "node_load5{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "load5-{{ip}}"
    },
    {
     "expr": "node_load15{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "load15-{{ip}}"
    }
   ]
  },
  { "title": "Memory 监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total 内存",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "主机 Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Shmem_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "shmem-{{ip}}"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "cache-{{ip}}"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "free-{{ip}}"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "buffer-{{ip}}"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "available-{{ip}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "total-{{ip}}"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "swap-total-{{ip}}"
    },
    {
     "expr": "node_memory_SwapFree_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "swap-free-{{ip}}"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "swap-cache-{{ip}}"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "slab-{{ip}}"
    },
    {
     "expr": "node_memory_KernelStack_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "kernel-stack-{{ip}}"
    },
    {
     "expr": "node_memory_Percpu_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "percpu-{{ip}}"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "vmalloc-used-{{ip}}"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"static\",ip=~\"$host_ip\"} -\nnode_memory_SReclaimable_bytes{job=\"static\",ip=~\"$host_ip\"} +\nnode_memory_KernelStack_bytes{job=\"static\",ip=~\"$host_ip\"} +\nnode_memory_Percpu_bytes{job=\"static\",ip=~\"$host_ip\"} +\nnode_memory_VmallocUsed_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "kernel-{{ip}}"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "committed-{{ip}}"
    }
   ]
  },
  {
   "title": "Used 内存 ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"static\",ip=~\"$host_ip\"} - node_memory_MemAvailable_bytes{job=\"static\",ip=~\"$host_ip\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  { "title": "VMStat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Swap读写",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpout{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval])*4096",
     "legendFormat": "pswpout-{{ip}}"
    },
    {
     "expr": "rate(node_vmstat_pswpin{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval])*4096",
     "legendFormat": "pswpin-{{ip}}"
    }
   ]
  },
  {
   "title": "内存回收",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgscan_kswapd{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval]) * 4096",
     "legendFormat": "kswapd-{{ip}}"
    },
    {
     "expr": "rate(node_vmstat_pgscan_direct{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval]) * 4096",
     "legendFormat": "direct-{{ip}}"
    },
    {
     "expr": "rate(node_vmstat_pgsteal_kswapd{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval]) * 4096",
     "legendFormat": "kswapd-steal-{{ip}}"
    },
    {
     "expr": "rate(node_vmstat_pgsteal_direct{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval]) * 4096",
     "legendFormat": "direct-steal-{{ip}}"
    },
    {
     "expr": "rate(node_vmstat_pgsteal_file{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval]) * 4096",
     "legendFormat": "file-steal-{{ip}}"
    },
    {
     "expr": "rate(node_vmstat_pgsteal_anon{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval]) * 4096",
     "legendFormat": "anon-steal-{{ip}}"
    }
   ]
  },
  {
   "title": "OOM 信号",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_oom_kill{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval])",
     "legendFormat": "oomkill-{{ip}}"
    }
   ]
  },
  {
   "title": "缺页统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgfault{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval])",
     "legendFormat": "pgfault-{{ip}}"
    },
    {
     "expr": "rate(node_vmstat_pgmajfault{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval])",
     "legendFormat": "pgmajfault-{{ip}}"
    }
   ]
  },
  { "title": "Disk 监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{ip=~\"$host_ip\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "read-{{device}}-{{ip}}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{ip=~\"$host_ip\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "write-{{device}}-{{ip}}"
    }
   ]
  },
  {
   "title": "读写带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{ip=~\"$host_ip\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "read-{{device}}-{{ip}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{ip=~\"$host_ip\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "write-{{device}}-{{ip}}"
    }
   ]
  },
  {
   "title": "读写时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{ip=~\"$host_ip\", device=~\"$device\"}[$__rate_interval])/clamp_min(rate(node_disk_reads_completed_total{ip=~\"$host_ip\",device=~\"$device\"}[$__rate_interval]),1)\n",
     "legendFormat": "read-{{device}}-{{ip}}"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{ip=~\"$host_ip\", device=~\"$device\"}[$__rate_interval])/clamp_min(rate(node_disk_writes_completed_total{ip=~\"$host_ip\",device=~\"$device\"}[$__rate_interval]),1)",
     "legendFormat": "write-{{device}}-{{ip}}"
    }
   ]
  },
  {
   "title": "IO 队列长度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{ip=~\"$host_ip\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}}-{{ip}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{ip=~\"$host_ip\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}}-{{ip}}"
    }
   ]
  },
  { "title": "PSI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Host Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate (node_pressure_cpu_waiting_seconds_total{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval])",
     "legendFormat": "cpu-some-{{ip}}"
    },
    {
     "expr": "rate (node_pressure_memory_waiting_seconds_total{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval])",
     "legendFormat": "mem-some-{{ip}}"
    },
    {
     "expr": "rate (node_pressure_memory_stalled_seconds_total{job=\"static\",ip=~\"$host_ip\"}[$__rate_interval])",
     "legendFormat": "mem-full-{{ip}}"
    },
    {
     "expr": "rate(node_pressure_stat_seconds_total{job=\"static\",ip=~\"$host_ip\",resource=\"swap\",scope=\"full\"}[$__rate_interval])",
     "legendFormat": "swap-full-{{ip}}"
    },
    {
     "expr": "rate(node_pressure_stat_seconds_total{job=\"static\",ip=~\"$host_ip\",resource=\"swap\",scope=\"some\"}[$__rate_interval])",
     "legendFormat": "swap-some-{{ip}}"
    }
   ]
  }
 ]
}